language: node_js
node_js:
    - 10
install:
    - yarn
cache:
    directories:
        - node_modules
script:
    - yarn test:unit
deploy:
    provider: heroku
    api_key: $HEROKU_API_KEY
    app: dante-fr-hub
    on:
        repo: pat64j/dante-front
